export const GAME_CONSTANTS = {
  MAX_PLAYERS: 4,
  MIN_PLAYERS: 1,
  DICE_COUNT: 5,
  MAX_ROLLS_PER_TURN: 3,
  DICE_MIN_VALUE: 1,
  DICE_MAX_VALUE: 6,
  TOTAL_CATEGORIES: 13,
} as const;

export const SCORE_CONSTANTS = {
  YACHT_BONUS: 50,
  UPPER_SECTION_BONUS: 35,
  UPPER_SECTION_BONUS_THRESHOLD: 63,
} as const;
